config:
  credentials: []
  project_repos:
    github.com/EOSC-synergy/sqaaas-tooling:
      branch: main
      repo: https://github.com/EOSC-synergy/sqaaas-tooling
    github.com/cyfronet-fid/pl-discovery-hub:
      branch: feat/122-get-silver-badge
      repo: https://github.com/cyfronet-fid/pl-discovery-hub/
environment:
  JPL_DOCKERFORCEBUILD: enabled
  JPL_KEEPGOING: enabled
sqa_criteria:
  QC.Acc:
    repos:
      github.com/cyfronet-fid/pl-discovery-hub git:
        commands:
        - /usr/bin/env sh .sqa/script.silly-orange-liger.sh
        container: qc.acc_stealthy-ecru-shrimp
  QC.Doc:
    repos:
      github.com/cyfronet-fid/pl-discovery-hub find_doc_files.py:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-razzmatazz-ray.sh
        container: qc.doc_slaphappy-crimson-zebu
      github.com/cyfronet-fid/pl-discovery-hub git:
        commands:
        - /usr/bin/env sh .sqa/script.messy-beige-paradise.sh
        container: qc.doc_baggy-peach-stingray
      github.com/cyfronet-fid/pl-discovery-hub markdownlint:
        commands:
        - /usr/bin/env sh .sqa/script.sleazy-amethyst-crab.sh
        container: qc.doc_hilly-azure-bulldog
  QC.Lic:
    repos:
      github.com/cyfronet-fid/pl-discovery-hub licensee:
        commands:
        - /usr/bin/env sh .sqa/script.pretty-tangerine-gerbil.sh
        container: qc.lic_homey-magnolia-snail
  QC.Met:
    repos:
      github.com/cyfronet-fid/pl-discovery-hub cff-converter-python:
        commands:
        - /usr/bin/env sh .sqa/script.goopy-charcoal-horse.sh
        container: qc.met_sunny-denim-fly
  QC.Sec:
    repos:
      github.com/cyfronet-fid/pl-discovery-hub bandit:
        commands:
        - /usr/bin/env sh .sqa/script.snoopy-coral-bison.sh
        container: qc.sec_woozy-peach-fowl
  QC.Sty:
    repos:
      github.com/cyfronet-fid/pl-discovery-hub flake8:
        commands:
        - /usr/bin/env sh .sqa/script.scanty-xanthic-oriole.sh
        container: qc.sty_cranky-lime-oyster
      github.com/cyfronet-fid/pl-discovery-hub hadolint:
        commands:
        - /usr/bin/env sh .sqa/script.breezy-azure-nightingale.sh
        container: qc.sty_scaly-corn-kingfisher
      github.com/cyfronet-fid/pl-discovery-hub jsonlint:
        commands:
        - /usr/bin/env sh .sqa/script.paltry-chestnut-monster.sh
        container: qc.sty_blurry-wheat-toad
  QC.Uni:
    repos:
      github.com/cyfronet-fid/pl-discovery-hub pytest:
        commands:
        - /usr/bin/env sh .sqa/script.shaggy-violet-burmese.sh
        container: qc.uni_snippy-aquamarine-lizard
  QC.Ver:
    repos:
      github.com/cyfronet-fid/pl-discovery-hub get_git_tags.py:
        commands:
        - /usr/bin/env sh .sqa/script.dorky-cream-chameleon.sh
        container: qc.ver_shabby-wisteria-caterpillar
timeout: 5400
